import "./globals.css";
import type { Metadata } from "next";
import ReduxProvider from "@/utils/store/Provider";
export const metadata: Metadata = {
  title: "Recent Video",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
